<a href="https://colab.research.google.com/github/aliawofford9317/LSAMP_Python_Course2024/blob/DanielaaVargas/Lesson_3c_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exercise 1**

Create a 3x3x3 array that contains all random numbers.
Using the previous array, square all the numbers in the array.

In [ ]:
import numpy as np

In [ ]:
np.random.seed(700)
Array = np.random.randint(10,size=(3,3,3)) #3 dimentional array
Array

array([[[7, 7, 1],
        [5, 2, 3],
        [8, 6, 0]],

       [[2, 6, 8],
        [8, 9, 4],
        [9, 1, 5]],

       [[4, 3, 2],
        [3, 0, 1],
        [2, 8, 6]]])

In [ ]:
SqArray = Array**2 #The square operation on an array is also an array (it is closed)
SqArray

array([[[49, 49,  1],
        [25,  4,  9],
        [64, 36,  0]],

       [[ 4, 36, 64],
        [64, 81, 16],
        [81,  1, 25]],

       [[16,  9,  4],
        [ 9,  0,  1],
        [ 4, 64, 36]]])

# **Exercise 2**
Create a new array using `arange`. This array should contain a total of 4 values.
Select only values in index 2 and index 4.
Change the value of index 3 to 99

In [ ]:
Arr = np.arange(4,12,2)
Arr

array([ 4,  6,  8, 10])

In [ ]:
print(Arr[1])
print(Arr[3])
Arr[2]=99
Arr

6
10


array([ 4,  6, 99, 10])

# **Exercise 3**
Create a new 4x4 array.
Select and print only the first two rows.
Select and print only the last two columns.
Select only the last two rows and first two columns.
Reshape the array into a 8x2 array.

In [ ]:
np.random.seed(700)
Cdot = np.random.randint(100,size=(4,4))
Cdot

array([[55,  7, 62, 49],
       [50, 35, 90, 61],
       [28,  8, 80, 50],
       [36, 81, 52,  3]])

In [ ]:
print("The first 2 rows are:\n") #Rows subarray
r = Cdot[:2]
r

The first 2 rows are:



array([[55,  7, 62, 49],
       [50, 35, 90, 61]])

In [ ]:
print("\nThe last two columns are:\n") #Columns subarray
c = Cdot[:4,2:4]
c


The last two columns are:



array([[62, 49],
       [90, 61],
       [80, 50],
       [52,  3]])

In [ ]:
Cdot.shape

(4, 4)

In [ ]:
Cdot[:4,:2]

array([[55,  7],
       [50, 35],
       [28,  8],
       [36, 81]])

In [ ]:
"""I'm not sure how to reshape a 4x4 array to an 8x2 array.
Is it okay if I just generate a new array with the same seed? """
np.random.seed(700)
np.random.randint(100,size=(8,2))

array([[55,  7],
       [62, 49],
       [50, 35],
       [90, 61],
       [28,  8],
       [80, 50],
       [36, 81],
       [52,  3]])

In [ ]:
"Or should Imaybe delete 2 columns and add 4 rows?"
np.random.seed(700)
DelC = Cdot[:4,:2]  #Deleting 2 columns
row = np.random.randint(100,size=(4,2)) #Creating new rows

np.vstack((DelC, row)) #Adding the new rows

array([[55,  7],
       [50, 35],
       [28,  8],
       [36, 81],
       [55,  7],
       [62, 49],
       [50, 35],
       [90, 61]])

# **Exercises for Participation Credit**


1.  Create a new random integer array with Numpy functions. Use a random seed to guarantee the same array every time. Array must be of size (20, 5).
2. Calculate the average value of the second column of the array created in exercise.
3. Calculate the sum of all elements in columns 3 and 4. You can use built in ufuncs and indexing.


In [ ]:
np.random.seed(10)
Gamma = np.random.randint(100,size=(20,5))
Gamma

array([[ 9, 15, 64, 28, 89],
       [93, 29,  8, 73,  0],
       [40, 36, 16, 11, 54],
       [88, 62, 33, 72, 78],
       [49, 51, 54, 77, 69],
       [13, 25, 13, 92, 86],
       [30, 30, 89, 12, 65],
       [31, 57, 36, 27, 18],
       [93, 77, 22, 23, 94],
       [11, 28, 74, 88,  9],
       [15, 18, 80, 71, 88],
       [11, 17, 46,  7, 75],
       [28, 33, 84, 96, 88],
       [44,  5,  4, 71, 88],
       [88, 50, 54, 34, 15],
       [77, 88, 15,  6, 85],
       [22, 11, 12, 92, 96],
       [62, 57, 79, 42, 57],
       [97, 50, 45, 40, 89],
       [73, 37,  0, 18, 23]])

In [ ]:
avg = np.mean(Gamma[:,1])
avg

38.8

In [ ]:
np.add.reduce(Gamma[:,2]) + np.add.reduce(Gamma[:,3])

1808

# **Exercises for Participation Credit (Continued)**

We will now use a simple IoT readings dataset for this exercise. This dataset contains IoT temperature readings, where the reading was made (room) and location (reading was outside or inside a room).

4. Open the data file IOT-temp.csv inside the iotdata-compressed file, you will need some program like 7zip or Winrar to uncompress this iotdata-compressed folder. Open this file with Pandas and create a new Dataframe with this data. Show the first 10 rows of data. Show the last 10 rows of data. Show data points for index 300 to 350.

5. Create a new dataframe from index 1000 to 2000. Rename column out/in to location. Rename colum room_id/id to room How many of these readings were made outside? How many were inside?

6. Split your new dataframe into readings that were made inside and readings that were made outside. Create a new dataframe with only inside readings. Create a new dataframe only with outside readings. Print the mean value of the temperature for both new dataframes.

7. Save both dataframes created in exercise 6 to csv files.

More information about the dataset for exercises 4 and 5 in this link

In [30]:
import pandas as pd

In [31]:
%%capture
def Fdata():
  import os, shutil
  cwd = os.getcwd()
  if os.path.exists("LSAMP_Python"):
    shutil.rmtree("LSAMP_Python")
  !git clone https://github.com/DanielaaVargas/LSAMP_Python.git
  for file in os.listdir("LSAMP_Python"):
    if file.endswith((".csv")):
      shutil.copy("LSAMP_Python/{}".format(file),cwd)
Fdata()

In [49]:
IOTtemp = pd.read_csv("IOT-temp.csv")
IOTtemp.head(10)

id  room_id/id        noted_date  temp  \
0  __export__.temp_log_196134_bd201015  Room Admin  08-12-2018 09:30    29   
1  __export__.temp_log_196131_7bca51bc  Room Admin  08-12-2018 09:30    29   
2  __export__.temp_log_196127_522915e3  Room Admin  08-12-2018 09:29    41   
3  __export__.temp_log_196128_be0919cf  Room Admin  08-12-2018 09:29    41   
4  __export__.temp_log_196126_d30b72fb  Room Admin  08-12-2018 09:29    31   
5  __export__.temp_log_196125_b0fa0b41  Room Admin  08-12-2018 09:29    31   
6  __export__.temp_log_196121_01544d45  Room Admin  08-12-2018 09:28    29   
7  __export__.temp_log_196122_f8b80a9f  Room Admin  08-12-2018 09:28    29   
8  __export__.temp_log_196111_6b7a0848  Room Admin  08-12-2018 09:26    29   
9  __export__.temp_log_196112_e134aebd  Room Admin  08-12-2018 09:26    29   

  out/in  
0     In  
1     In  
2    Out  
3    Out  
4     In  
5     In  
6     In  
7     In  
8     In  
9     In

In [50]:
IOTtemp.tail(10)

id  room_id/id        noted_date  \
97596  __export__.temp_log_111718_05b8d88d  Room Admin  28-07-2018 07:07   
97597   __export__.temp_log_96677_28b0568f  Room Admin  28-07-2018 07:07   
97598  __export__.temp_log_110269_898976fc  Room Admin  28-07-2018 07:07   
97599  __export__.temp_log_124155_da310d7b  Room Admin  28-07-2018 07:07   
97600  __export__.temp_log_121414_9004c748  Room Admin  28-07-2018 07:07   
97601   __export__.temp_log_91076_7fbd08ca  Room Admin  28-07-2018 07:07   
97602  __export__.temp_log_147733_62c03f31  Room Admin  28-07-2018 07:07   
97603  __export__.temp_log_100386_84093a68  Room Admin  28-07-2018 07:06   
97604  __export__.temp_log_123297_4d8e690b  Room Admin  28-07-2018 07:06   
97605  __export__.temp_log_133741_32958703  Room Admin  28-07-2018 07:06   

       temp out/in  
97596    32    Out  
97597    31     In  
97598    31     In  
97599    32    Out  
97600    31     In  
97601    31     In  
97602    31     In  
97603    31     In  
97604    31     In  
97605    31     In

In [51]:
IOTtemp.iloc[300:351]

id  room_id/id        noted_date  temp  \
300  __export__.temp_log_195177_d33112e6  Room Admin  08-12-2018 04:20    36   
301  __export__.temp_log_195176_b9e9dbb5  Room Admin  08-12-2018 04:19    36   
302  __export__.temp_log_195175_07586658  Room Admin  08-12-2018 04:19    29   
303  __export__.temp_log_195174_72be5b21  Room Admin  08-12-2018 04:19    29   
304  __export__.temp_log_195167_e8fa1d81  Room Admin  08-12-2018 04:18    36   
305  __export__.temp_log_195166_abde5476  Room Admin  08-12-2018 04:17    36   
306  __export__.temp_log_195165_99840a1c  Room Admin  08-12-2018 04:17    29   
307  __export__.temp_log_195164_4ff2549b  Room Admin  08-12-2018 04:17    29   
308  __export__.temp_log_195158_b42b3e8b  Room Admin  08-12-2018 04:16    37   
309  __export__.temp_log_195159_f47207dc  Room Admin  08-12-2018 04:15    37   
310  __export__.temp_log_195153_1fbbf291  Room Admin  08-12-2018 04:14    37   
311  __export__.temp_log_195152_0912cefe  Room Admin  08-12-2018 04:14    37   
312  __export__.temp_log_195146_7b25971b  Room Admin  08-12-2018 04:11    29   
313  __export__.temp_log_195147_1be17b84  Room Admin  08-12-2018 04:11    29   
314  __export__.temp_log_195139_3ae05a53  Room Admin  08-12-2018 04:09    29   
315  __export__.temp_log_195138_4c528c59  Room Admin  08-12-2018 04:09    29   
316  __export__.temp_log_195132_88aa5b76  Room Admin  08-12-2018 04:08    36   
317  __export__.temp_log_195133_2e87c162  Room Admin  08-12-2018 04:08    36   
318  __export__.temp_log_195131_f2bc3d99  Room Admin  08-12-2018 04:07    29   
319  __export__.temp_log_195130_e2128775  Room Admin  08-12-2018 04:07    29   
320  __export__.temp_log_195119_950652c4  Room Admin  08-12-2018 04:04    36   
321  __export__.temp_log_195118_818af56d  Room Admin  08-12-2018 04:04    36   
322  __export__.temp_log_195117_0310e550  Room Admin  08-12-2018 04:03    29   
323  __export__.temp_log_195116_d31657b9  Room Admin  08-12-2018 04:03    29   
324  __export__.temp_log_195114_0302145d  Room Admin  08-12-2018 04:03    30   
325  __export__.temp_log_195115_7de36953  Room Admin  08-12-2018 04:03    30   
326  __export__.temp_log_195109_8368b845  Room Admin  08-12-2018 04:02    36   
327  __export__.temp_log_195108_1520c580  Room Admin  08-12-2018 04:02    36   
328  __export__.temp_log_195107_e9bd831a  Room Admin  08-12-2018 04:01    29   
329  __export__.temp_log_195106_1161a490  Room Admin  08-12-2018 04:01    29   
330  __export__.temp_log_195099_94fff493  Room Admin  08-12-2018 04:00    36   
331  __export__.temp_log_195098_6d37924f  Room Admin  08-12-2018 04:00    36   
332  __export__.temp_log_195097_7fb4f591  Room Admin  08-12-2018 03:59    29   
333  __export__.temp_log_195096_206056de  Room Admin  08-12-2018 03:59    29   
334  __export__.temp_log_195091_b1536e7c  Room Admin  08-12-2018 03:59    30   
335  __export__.temp_log_195090_a0dcc099  Room Admin  08-12-2018 03:59    30   
336  __export__.temp_log_195088_79fc3ddd  Room Admin  08-12-2018 03:58    36   
337  __export__.temp_log_195089_c24769a4  Room Admin  08-12-2018 03:58    36   
338  __export__.temp_log_195087_2785ae71  Room Admin  08-12-2018 03:57    29   
339  __export__.temp_log_195086_09d4d68c  Room Admin  08-12-2018 03:57    29   
340  __export__.temp_log_195083_ea67bfee  Room Admin  08-12-2018 03:55    29   
341  __export__.temp_log_195082_07be8615  Room Admin  08-12-2018 03:55    29   
342  __export__.temp_log_195076_e7d5b616  Room Admin  08-12-2018 03:54    36   
343  __export__.temp_log_195077_fe2b50d1  Room Admin  08-12-2018 03:54    36   
344  __export__.temp_log_195075_9de50453  Room Admin  08-12-2018 03:53    29   
345  __export__.temp_log_195074_8841b10a  Room Admin  08-12-2018 03:53    29   
346  __export__.temp_log_195071_7362ce83  Room Admin  08-12-2018 03:53    30   
347  __export__.temp_log_195069_1cc7bf5d  Room Admin  08-12-2018 03:53    30   
348  __export__.temp_log_195066_732e758f  Room Admin  08-12-2018 03:51    29   
349  __export__.temp_log_195067_023052

In [52]:
DataF = IOTtemp.iloc[1000:2001]
DataF

id  room_id/id        noted_date  temp  \
1000  __export__.temp_log_193515_7c7f482c  Room Admin  07-12-2018 18:20    29   
1001  __export__.temp_log_193514_04dce9c2  Room Admin  07-12-2018 18:20    29   
1002  __export__.temp_log_193511_26e001f0  Room Admin  07-12-2018 18:18    38   
1003  __export__.temp_log_193510_9b2d9c4d  Room Admin  07-12-2018 18:18    38   
1004  __export__.temp_log_193509_47e74171  Room Admin  07-12-2018 18:18    29   
...                                   ...         ...               ...   ...   
1996  __export__.temp_log_190700_598349c7  Room Admin  07-12-2018 01:25    33   
1997  __export__.temp_log_190699_439d5931  Room Admin  07-12-2018 01:25    33   
1998  __export__.temp_log_190698_b2f37148  Room Admin  07-12-2018 01:23    32   
1999  __export__.temp_log_190697_25aef9b9  Room Admin  07-12-2018 01:23    32   
2000  __export__.temp_log_190694_11b48341  Room Admin  07-12-2018 01:21    31   

     out/in  
1000     In  
1001     In  
1002    Out  
1003    Out  
1004     In  
...     ...  
1996    Out  
1997    Out  
1998    Out  
1999    Out  
2000    Out  

[1001 rows x 5 columns]

In [53]:
DataF.rename(columns={"out/in":"location", "room_id/id":"room"}, inplace=True)
DataF

<ipython-input-53-9d4a2ed76c9f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  DataF.rename(columns={"out/in":"location", "room_id/id":"room"}, inplace=True)


id        room        noted_date  temp  \
1000  __export__.temp_log_193515_7c7f482c  Room Admin  07-12-2018 18:20    29   
1001  __export__.temp_log_193514_04dce9c2  Room Admin  07-12-2018 18:20    29   
1002  __export__.temp_log_193511_26e001f0  Room Admin  07-12-2018 18:18    38   
1003  __export__.temp_log_193510_9b2d9c4d  Room Admin  07-12-2018 18:18    38   
1004  __export__.temp_log_193509_47e74171  Room Admin  07-12-2018 18:18    29   
...                                   ...         ...               ...   ...   
1996  __export__.temp_log_190700_598349c7  Room Admin  07-12-2018 01:25    33   
1997  __export__.temp_log_190699_439d5931  Room Admin  07-12-2018 01:25    33   
1998  __export__.temp_log_190698_b2f37148  Room Admin  07-12-2018 01:23    32   
1999  __export__.temp_log_190697_25aef9b9  Room Admin  07-12-2018 01:23    32   
2000  __export__.temp_log_190694_11b48341  Room Admin  07-12-2018 01:21    31   

     location  
1000       In  
1001       In  
1002      Out  
1003      Out  
1004       In  
...       ...  
1996      Out  
1997      Out  
1998      Out  
1999      Out  
2000      Out  

[1001 rows x 5 columns]

In [54]:
DataIn = DataF.loc[DataF["location"]=="In"]
print(f'There were {len(DataIn)} measurements inside.')

There were 565 measurements inside.


In [56]:
DataOut = DataF.loc[DataF["location"]=="Out"]
print(f'There were {len(DataOut)} measurements outside.')

There were 436 measurements outside.


In [62]:
print(DataIn)

                                       id        room        noted_date  temp  \
1000  __export__.temp_log_193515_7c7f482c  Room Admin  07-12-2018 18:20    29   
1001  __export__.temp_log_193514_04dce9c2  Room Admin  07-12-2018 18:20    29   
1004  __export__.temp_log_193509_47e74171  Room Admin  07-12-2018 18:18    29   
1005  __export__.temp_log_193508_041bf6bc  Room Admin  07-12-2018 18:18    29   
1006  __export__.temp_log_193503_e8b2d4aa  Room Admin  07-12-2018 18:16    29   
...                                   ...         ...               ...   ...   
1963  __export__.temp_log_190820_fdda325d  Room Admin  07-12-2018 02:27    31   
1966  __export__.temp_log_190799_6401ad73  Room Admin  07-12-2018 02:19    30   
1967  __export__.temp_log_190800_3ffc2c5f  Room Admin  07-12-2018 02:19    30   
1968  __export__.temp_log_190793_cb29f220  Room Admin  07-12-2018 02:17    29   
1969  __export__.temp_log_190794_08d54ca2  Room Admin  07-12-2018 02:17    29   

     location  
1000       

In [67]:
Itemp = DataIn['temp']
Itemp.mean()

28.486725663716815

In [70]:
Otemp = DataOut['temp']
Otemp.mean()

35.96559633027523

In [71]:
DataIn.to_csv("Inside.csv")
DataOut.to_csv("Outside.csv")

In [73]:
import os
print(os.getcwd())

/content
